org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

# Project
version=1.0.1
group=by.deokma
java_version=17

# Mod info
mod_id=notely
mod_name=Notely
mod_author=Deokma
license=MPL-2.0
credits=
description=A client-side notepad mod with Markdown rendering and pinnable sticky notes.

# Minecraft
minecraft_version=1.18.2
minecraft_version_range=[1.18.2, 1.19)
parchment_minecraft=1.18.2
parchment_version=2022.11.06

# Fabric
fabric_loader_version=0.14.21
fabric_version=0.77.0+1.18.2

# Forge
forge_version=40.2.21
forge_loader_version_range=[40,)

loom.mojangMappingsLicense.accepted=true
